/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type InquiryId = bigint;
export interface InquiryInput {
  'propertyType' : string,
  'name' : string,
  'message' : string,
  'phone' : string,
}
export interface Property {
  'id' : PropertyId,
  'title' : string,
  'verified' : boolean,
  'propertyType' : string,
  'studentFriendly' : boolean,
  'description' : string,
  'amenities' : Array<string>,
  'furnished' : boolean,
  'imageUrl' : string,
  'price' : bigint,
  'nearbyCoaching' : Array<string>,
  'location' : string,
}
export type PropertyId = bigint;
export interface _SERVICE {
  'getProperties' : ActorMethod<[], Array<Property>>,
  'submitInquiry' : ActorMethod<[InquiryInput], InquiryId>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];