/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PropertyId = IDL.Nat;
export const Property = IDL.Record({
  'id' : PropertyId,
  'title' : IDL.Text,
  'verified' : IDL.Bool,
  'propertyType' : IDL.Text,
  'studentFriendly' : IDL.Bool,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'furnished' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
  'nearbyCoaching' : IDL.Vec(IDL.Text),
  'location' : IDL.Text,
});
export const InquiryInput = IDL.Record({
  'propertyType' : IDL.Text,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const InquiryId = IDL.Nat;

export const idlService = IDL.Service({
  'getProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'submitInquiry' : IDL.Func([InquiryInput], [InquiryId], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PropertyId = IDL.Nat;
  const Property = IDL.Record({
    'id' : PropertyId,
    'title' : IDL.Text,
    'verified' : IDL.Bool,
    'propertyType' : IDL.Text,
    'studentFriendly' : IDL.Bool,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'furnished' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
    'nearbyCoaching' : IDL.Vec(IDL.Text),
    'location' : IDL.Text,
  });
  const InquiryInput = IDL.Record({
    'propertyType' : IDL.Text,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const InquiryId = IDL.Nat;
  
  return IDL.Service({
    'getProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'submitInquiry' : IDL.Func([InquiryInput], [InquiryId], []),
  });
};

export const init = ({ IDL }) => { return []; };